const PDFDocument = require('pdfkit');

const generateFinancialStatement = (chama, contributions, loans, memberSummary) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc.fillColor('#16a34a').fontSize(24).text('FunguApp', { align: 'center' });
    doc.fillColor('#333').fontSize(16).text('Financial Statement', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666').text(`Generated on: ${new Date().toLocaleDateString('en-KE', { day: 'numeric', month: 'long', year: 'numeric' })}`, { align: 'center' });

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#16a34a').stroke();
    doc.moveDown();

    // Chama Info
    doc.fillColor('#16a34a').fontSize(14).text('Chama Information');
    doc.moveDown(0.5);
    doc.fillColor('#333').fontSize(11);
    doc.text(`Name: ${chama.name}`);
    doc.text(`Description: ${chama.description || 'N/A'}`);
    doc.text(`Monthly Contribution: KES ${chama.rules?.contributionAmount?.toLocaleString()}`);
    doc.text(`Contribution Frequency: ${chama.rules?.contributionFrequency}`);
    doc.text(`Total Members: ${chama.members?.length}`);
    doc.text(`Current Balance: KES ${chama.balance?.toLocaleString()}`);
    doc.text(`Invite Code: ${chama.inviteCode}`);

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown();

    // Member Summary
    doc.fillColor('#16a34a').fontSize(14).text('Member Contribution Summary');
    doc.moveDown(0.5);

    if (memberSummary.length === 0) {
      doc.fillColor('#666').fontSize(11).text('No contributions recorded yet.');
    } else {
      memberSummary.forEach((m, i) => {
        doc.fillColor('#333').fontSize(11);
        doc.text(`${i + 1}. ${m.member?.name} — KES ${m.totalContributed?.toLocaleString()} (${m.contributions} payment${m.contributions > 1 ? 's' : ''})`);
      });
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown();

    // Contributions
    doc.fillColor('#16a34a').fontSize(14).text('Contribution Ledger');
    doc.moveDown(0.5);

    if (contributions.length === 0) {
      doc.fillColor('#666').fontSize(11).text('No contributions recorded yet.');
    } else {
      contributions.forEach(c => {
        doc.fillColor('#333').fontSize(10);
        doc.text(
          `${new Date(c.createdAt).toLocaleDateString()} | ${c.member?.name} | KES ${c.amount?.toLocaleString()} | Ref: ${c.mpesaRef || 'N/A'} | ${c.status}`,
          { lineGap: 4 }
        );
      });
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown();

    // Loans
    doc.fillColor('#16a34a').fontSize(14).text('Loan Records');
    doc.moveDown(0.5);

    if (loans.length === 0) {
      doc.fillColor('#666').fontSize(11).text('No loans recorded yet.');
    } else {
      loans.forEach(l => {
        doc.fillColor('#333').fontSize(10);
        doc.text(
          `${new Date(l.createdAt).toLocaleDateString()} | ${l.member?.name} | KES ${l.amount?.toLocaleString()} | Repayable: KES ${l.totalRepayable?.toLocaleString()} | Status: ${l.status}`,
          { lineGap: 4 }
        );
        doc.fillColor('#666').fontSize(9).text(`  Reason: ${l.reason}`, { lineGap: 6 });
      });
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#16a34a').stroke();
    doc.moveDown();

    // Footer
    doc.fillColor('#666').fontSize(9).text(
      'This document was automatically generated by FunguApp. It is a true and accurate record of all transactions recorded on the platform.',
      { align: 'center' }
    );
    doc.text('FunguApp — Transparent Chama Management', { align: 'center' });

    doc.end();
  });
};

module.exports = { generateFinancialStatement };